- name: Copy zsh configuration
  copy:
    src: "{{ project_root_dir }}/oh-my-zsh/.zshrc"
    dest: "{{ home_dir }}/.zshrc"

- name: Copy tmux configuration
  copy:
    src: "{{ project_root_dir }}/.tmux.conf"
    dest: "{{ home_dir }}/.tmux.conf"

- name: Copy Oh-my-zsh theme
  copy:
    src: "{{ project_root_dir }}/oh-my-zsh/custom-gnzh.zsh-theme"
    dest: "{{ oh_my_zsh_dir }}/custom/themes/custom-gnzh.zsh-theme"
