- name: Install desktop utilities
  become: true
  apt:
    name:
      - feh
      - flameshot
      - ripgrep
      - thunar
      - xclip
      - xdotool
      - lxappearance
      - i3
      - polybar
      - arandr
      - brightnessctl
      - tmux
      - pipx
      - network-manager-gnome
      - rofi
    state: present
    update_cache: true

- name: Clone fzf repository
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ ansible_env.HOME }}/.fzf"
    depth: 1
    update: yes

- name: Install fzf
  command: "{{ ansible_env.HOME }}/.fzf/install --all --no-update-rc"
