#!/usr/bin/env zsh

selected_context=$(kubectl config get-contexts | awk '{if (NR!=1) print $2}' | fzf)

if [ -n "$selected_context" ]
then
    k9s --context "$selected_context"
else
    echo "send context pls ಥ_ಥ"
fi

