---
- name: Install i3 window manager environment
  hosts: localhost
  connection: local
  become: false

  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    config_dir: "{{ home_dir }}/.config"

  tasks:
    # Polybar configuration
    - name: Ensure polybar config directory exists
      file:
        path: "{{ config_dir }}/polybar"
        state: directory
        mode: '0755'

    - name: Copy polybar configuration
      copy:
        src: "{{ playbook_dir }}/../polybar/"
        dest: "{{ config_dir }}/polybar/"
        directory_mode: '0755'

    - name: Find polybar scripts
      find:
        paths: "{{ config_dir }}/polybar"
        patterns: "*.sh"
        recurse: yes
      register: polybar_scripts

    - name: Make polybar scripts executable
      file:
        path: "{{ item.path }}"
        mode: '0755'
      with_items: "{{ polybar_scripts.files }}"
      when: polybar_scripts.files | length > 0

    # Picom configuration
    - name: Ensure picom config directory exists
      file:
        path: "{{ config_dir }}/picom"
        state: directory
        mode: '0755'

    - name: Copy picom configuration
      copy:
        src: "{{ playbook_dir }}/../picom/"
        dest: "{{ config_dir }}/picom/"
        directory_mode: '0755'

    # i3 configuration
    - name: Ensure i3 config directory exists
      file:
        path: "{{ config_dir }}/i3"
        state: directory
        mode: '0755'

    - name: Copy i3 configuration file
      copy:
        src: "{{ playbook_dir }}/../i3/config"
        dest: "{{ config_dir }}/i3/config"

    - name: Copy i3 wallpaper
      copy:
        src: "{{ playbook_dir }}/../i3/wp7041138-golang-wallpapers2.png"
        dest: "{{ config_dir }}/i3/wallpaper.png"

