---
- name: Install kitty configuration
  hosts: localhost
  connection: local
  become: false

  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    config_dir: "{{ home_dir }}/.config"

  tasks:
    # Kitty configuration
    - name: Ensure kitty config directory exists
      file:
        path: "{{ config_dir }}/kitty"
        state: directory
        mode: '0755'

    - name: Copy kitty configuration
      copy:
        src: "{{ playbook_dir }}/../kitty/"
        dest: "{{ config_dir }}/kitty/"
        directory_mode: '0755'

